<?php
// Habilitar CORS para permitir solicitudes desde cualquier origen
//header("Access-Control-Allow-Origin: *");
//header("Access-Control-Allow-Methods: GET, POST, OPTIONS");
//header("Access-Control-Allow-Headers: Origin, Content-Type, X-Auth-Token, Authorization");


$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');

if ($customerSession->isLoggedIn()) {
    $customerName = $customerSession->getCustomer()->getName();
    $customerEmail = $customerSession->getCustomer()->getEmail();
    $customerIdentification = $customerSession->getCustomer()->getIdentificationCustomer();

    //echo "¡Hola, " . $customerName . "!<br>";
    //echo "Correo electrónico: " . $customerEmail . "!<br>";
    //echo "Cédula / RUC: " . $customerIdentification;

} else {
    echo "¡Hola, visitante!";

    $customerName = "";
    $customerEmail = "";
    $customerIdentification = "";
  }

$token = "111111";

$escapedCustomerIdentification = urlencode($customerIdentification);
$escapedToken = urlencode($token);

$iframeSrc = "https://credito.siglo21.net:8011?&ruc=$escapedCustomerIdentification&token=$escapedToken";
?>

<script>
fetch('https://jsonplaceholder.typicode.com/posts', {
  method: 'POST',
  body: JSON.stringify({
    title: 'qui qui voluptates illo iste minima',
    body: 'aspernatur expedita soluta quo ab ut similique\nexpedita dolores amet\nsed temporibus distinctio magnam saepe deleniti\nomnis facilis nam ipsum natus sint similique omnis',
    userId: 10,
  }),
  headers: {
    'Content-type': 'application/json; charset=UTF-8',
  },
})
  .then((response) => response.json())
  .then((json) => console.log(json));
</script>


<iframe src="<?php echo $iframeSrc; ?>" width="100%" height="1270" style="border: none;"></iframe>